export const PICKME_EPISODES = [
  {
    id: 1, label: "Episode 1", panelists: "Hoezay · K Sebastian · Abhish Mathew",
    categories: [
      { name: "How Can She Slap?", question: "Nothing matches the prolific slap-taking ability of ex-Delhi CM Arvind Kejriwal. Which of the following did NOT happen?", options: ["Slapped in 2014", "Slapped in 2016", "Slapped in 2019", "Slapped with corruption charges and ED"], answer: "Slapped in 2016", explanation: "In 2016 only ink was thrown at him — not a physical slap. The 2014 and 2019 incidents were actual slaps." },
      { name: "AIB", question: "Which of the following AIB members is the funniest?", options: ["Tanmay Bhat", "Gursimran Khamba", "Rohan Joshi", "Ashish Shakya"], answer: "Tanmay Bhat", explanation: "Khamba declared Tanmay the funniest — also funny because Khamba himself is one of the options." },
      { name: "Indian Culture", isTrap: true, question: null, options: [], answer: "Minus 20 for picking this", explanation: "Picking 'Indian Culture' triggered an instant -20 penalty. How dare you question Indian Culture." },
      { name: "Baking Accident", question: "In front of which bakery in Bandra did Salman Khan's hit-and-run accident happen?", options: ["A1 Bakery", "American Express Bakery", "J. Harsh & Co.", "Hit and Run Bakery"], answer: "American Express Bakery", explanation: "The 2002 hit-and-run near Salman Khan's Galaxy apartment in Bandra occurred in front of American Express Bakery on Hill Road." },
      { name: "Children's Books", question: "Which of the following is a real Harry Potter adult parody film?", options: ["Harry Potter and the Gobbling of Cock", "Harry Potter and the Philosopher's Bone", "Hairy Cocker and the Deathly Holes", "Hori Potter and the Soft Balls"], answer: "Hori Potter and the Soft Balls", explanation: "The real parody is 'Hori Potter and the Soft Balls' — also available in 3D. The others were too lazy to be real." },
      { name: "Useless Brothers", question: "After declaring bankruptcy in 2020, what percentage of Anil Ambani's ₹47,251 crore debt was he asked to repay by the NCLT in 2023?", options: [], answer: "0.92%", explanation: "Despite owing ₹47,251 crore, the NCLT only demanded 0.92%. The limit to success truly is imagination." },
      { name: "21st Century Poets", question: "Yo Yo Honey Singh notoriously rhymed a body organ with an Indian street fried snack. What snack?", options: [], answer: "Pakoda", explanation: "Honey Singh rhymed a male body part with pakoda in a real song lyric. Spotify hides this from you." },
      { name: "Modi Ji", question: "What is the name of the plus-sized doctor character in Taarak Mehta Ka Ooltah Chashmah?", options: [], answer: "Dr. Haathi", explanation: "The plus-sized doctor character is called Dr. Haathi. His wife is Komal Haathi. The show preaches inclusivity then names its character 'Elephant'." },
      { name: "Punchable Face", question: "Ranveer Allahbadia is a podcaster known for asking a wide variety of questions. Which of the following has he NOT asked?", options: ["Aapko khaana pasand hai? (Do you like food?)", "Are Punjabi people in the Illuminati?", "Would you rather [redacted for legal reasons]", "If a woman has sex, is it like she loses some energy?"], answer: "Are Punjabi people in the Illuminati?", explanation: "Options A, C, and D are real questions from his podcasts. The Illuminati-Punjabi question is the fabricated one. We think." },
    ]
  },

  {
    id: 2, label: "Episode 2", panelists: "Karunesh Talwar · Anirban Das · Shamik Chakravarti",
    categories: [
      { name: "AIB", question: "Afghanistan International Bank (AIB) is the largest bank in Afghanistan with 35 branches. Who of the following is NOT a member of AIB management?", options: ["Rami Yusufi", "Abdullah Abdullah", "Michael Cunningham", "Lalit Kumar Jha"], answer: "Abdullah Abdullah", explanation: "Abdullah Abdullah is a former Foreign Affairs Minister of Afghanistan — a politician, nothing to do with the bank's management." },
      { name: "Bong Ki Baat", question: "Which of the following is NOT a real Mamata Banerjee quote?", options: ["Ka ka ji", "Aap rock leke khada hoga, hum kuchush kuchush karke usko kaat denge", "Cashless ke naam pe baseless ho gaya aur faceless ho gaya", "Shabba khair abba khair joy Bangla"], answer: "Shabba khair abba khair joy Bangla", explanation: "All the other bizarre-sounding quotes are real Mamata Banerjee quotes. 'Shabba khair abba khair' is the fake one." },
      { name: "Salman Bhai", question: "The Satanic Verses returned to Indian bookstores after a 36-year ban. What was the reason the ban no longer stands?", options: [], answer: "The government lost the original ban order and could not find it to renew it", explanation: "Bureaucracy at its finest — they simply misplaced the original ban order. Salman Rushdie is free by accident." },
      { name: "Mughal Dynasty", question: "Along with having a son named Taimur, what was the worst thing that happened to Saif Ali Khan in 2025?", options: ["Bhopal Palace declared enemy property", "Getting stabbed by an intruder", "Ibrahim Ali Khan acting in a film", "Sara Ali Khan in Metro In Dino"], answer: "Getting stabbed by an intruder", explanation: "Saif Ali Khan was actually stabbed at his Mumbai home in early 2025. Objectively the worst thing on the list." },
      { name: "Mads of Bollywood", question: "Who is Kangana Ranaut talking about in this quote: 'O chamcha, chal tu jinki chaat chaat ke kaam leta hai na, main unki roz bajati hoon, zyada mat uchal'?", options: ["Hrithik Roshan", "Diljit Dosanjh", "Rajeev Masand", "People of Manali"], answer: "Diljit Dosanjh", explanation: "Directed at Diljit during the farmers' protest when he was standing up for Punjabi rights. Kangana disagreed loudly." },
      { name: "PM Modi", isTrap: true, question: null, options: [], answer: "Minus 24 for picking this", explanation: "How dare you pick PM Modi. Instant -24 points. No question asked." },
      { name: "Man's Best Friend", question: "What breed of dog does the right-wing ecosystem call Dhruv Rathee?", options: ["Pomeranian", "French Poodle", "German Shepherd", "Shih Tzu"], answer: "German Shepherd", explanation: "He lives in Germany, hence 'German Shepherd' — implying he acts as a loyal guard dog for foreign ideology." },
      { name: "Higher Education", question: "Which of the following is the odd one out and why? IIT-JEE, UPSC, CA, NEET", options: ["IIT-JEE", "UPSC", "CA", "NEET"], answer: "NEET", explanation: "NEET is the only exam TVF has not yet made a web series about. Kota Factory, Aspirants, Half CA all exist. NEET is still waiting." },
      { name: "Korean Music", question: "Music composer Pritam is known for both inspired and original songs. Which of the following songs is an original composition by Pritam?", options: ["Badtameez Dil", "Ae Dil Hai Mushkil", "Zara Zara Touch Me", "Bhool Bhulaiyaa title track"], answer: "Channa Mereya", explanation: "Pritam originally composed Channa Mereya for Bajrangi Bhaijaan but Salman rejected it. It went to Ae Dil Hai Mushkil and became massive. The others are largely 'inspired' compositions." },
    ]
  },

  {
    id: 3, label: "Episode 3", panelists: "Raunak Rajani · Gurleen Pannu · Amit Tandon",
    categories: [
      { name: "Civil Engineering", question: "Which Bollywood singer's songs were discovered on Osama Bin Laden's hard drive by the CIA?", options: [], answer: "Alka Yagnik", explanation: "When the US raided the Abbottabad compound, Alka Yagnik's songs were found on Bin Laden's hard drive. She reportedly said 'Shayad Osama ke andar bhi ek chhota sa kalakar tha'." },
      { name: "Modi Ji", question: "Narendra Modi was recently seen at a lavish party in the UK singing a song with fugitive Vijay Mallya. What song were they singing?", options: ["Oops I Did It Again", "I Did It My Way", "Apna Sapna Money Money", "Fatela Jeb Bhar Jaega"], answer: "I Did It My Way", explanation: "Modi and Mallya were reportedly spotted together at a UK party singing Frank Sinatra's 'I Did It My Way' — a fitting choice given the circumstances." },
      { name: "Oscar Snubs", question: "Which of the following is NOT a real Bhojpuri film?", options: ["Gamchha Wala I Love You", "Biwi Tumhari Bachche Hamare", "Dulhan Chahiye Pakistani Role", "Riksha Wala I Love You"], answer: "Gamchha Wala I Love You", explanation: "The real one is 'Riksha Wala I Love You'. 'Gamchha Wala I Love You' is fabricated. 'Biwi Tumhari Bachche Hamare' and 'Dulhan Chahiye Pakistani Role' are painfully real Bhojpuri films." },
      { name: "Arts", isTrap: true, question: null, options: [], answer: "Minus 20 for picking Arts", explanation: "Picking Arts triggers an instant -20 penalty. 'Who picked Arts? This is why you're here — learn AI, you picked Arts.'" },
      { name: "Wao Skin Science", isTrap: true, question: null, options: [], answer: "+20 — sponsor category, no real question", explanation: "Wao Skin Science was the episode sponsor. Picking this triggered the sponsored segment with an ad read. +20 points awarded for picking it." },
      { name: "General Knowledge", question: "What is the most useless thing in the world?", options: ["Script writer in a Salman film", "Heroine in a Salman film", "Audience in a Salman film", "CRED points"], answer: "CRED points", explanation: "CRED points accumulate endlessly but can barely be redeemed for anything of actual value. Very close competition from the Salman options." },
      { name: "Mission Star", question: "Which of the following is NOT a real restaurant in Delhi?", options: ["Mere Babu Ne Khaana Khaaya", "Tandoori", "Wah Mote Wah", "Maa Ke Pakode"], answer: "Maa Ke Pakode", explanation: "Mere Babu Ne Khaana Khaaya, Tandoori, and Wah Mote Wah actually exist in Delhi. Maa Ke Pakode is the made-up one." },
      { name: "Canada", question: "Babbu Maan ne revolver chak kyun si? (Why did Babbu Maan pick up a revolver?)", options: [], answer: "Kabza lena hai (To take possession — referencing his famous song)", explanation: "A Punjabi lyric trivia question about Babbu Maan. The answer references his song about 'kabza' (possession). Raunak joined in with the singing and got +20." },
      { name: "Over Achievers", question: "Abhishek Bachchan, along with being a disappointment to his father, also holds a Guinness World Record. What for?", options: [], answer: "Most public appearances by a film star in 12 hours", explanation: "He holds the Guinness record for most public appearances by a film star in 12 hours — achieved while promoting Delhi 6 by visiting 7 cities in one day." },
    ]
  },

  {
    id: 4, label: "Episode 4", panelists: "Azeem Banatwalla · Varun Thakur · Kautuk Srivastava",
    categories: [
      { name: "Plants", question: "In 2022, Smriti Irani authored her first book. What was the title of her debut novel?", options: ["Kyunki Minister Bhi Kabhi Actor Thi", "Meri Aandhi Aur Rahul Gandhi", "Lal Salaam", "Main Tulsi Tere Aangan Ki"], answer: "Lal Salaam", explanation: "Smriti Irani's debut novel is 'Lal Salaam' — an ironic title given her very strong anti-left political stance as a BJP minister." },
      { name: "Struggling Actor", panelSpecific: true, question: "Which of the following roles has Varun Thakur NOT played?", options: ["Hero ka dost in Jab Tak Hai Jaan", "Casting assistant in Veer", "Only friend to Kautuk Srivastava", "A son his father can be proud of"], answer: "A son his father can be proud of", explanation: "A joke at his expense — he's played hero's friend, casting assistant, and is Kautuk's friend. 'A son his father can be proud of' is the one role he hasn't played." },
      { name: "Papa the Great", question: "ICC Chairman Jay Shah is beloved by all cricket fans. What is he lovingly called after an entertaining game?", options: ["Script Writer", "Chhota Mota Bhai", "Greek God", "A meritorious candidate totally deserving of his position"], answer: "Script Writer", explanation: "Jay Shah is called 'Script Writer' — whenever a cricket match goes conveniently India's way, fans joke that Jay Shah wrote the script." },
      { name: "National Monuments", question: "Antilia is built on land sold for ₹230 million in 2002 at a fraction of the market value. What was this land originally allocated for?", options: ["Orphanage for underprivileged children", "Rehabilitation of abused trees", "Charity hospital for cancer patients", "Another blight on Mumbai's skyline"], answer: "Charity hospital for cancer patients", explanation: "The land on which Antilia stands was originally allocated for a charity hospital for cancer patients before being acquired and used for Mukesh Ambani's private residence." },
      { name: "White People", question: "Abbas-Mastan are famous Bollywood directors known for wearing white. They also have a lesser-known third brother. What is his name?", options: ["Saifuddin Varmawala", "Mohammed Varmawala", "Hussain Varmawala", "Azeem Banatwalla"], answer: "Hussain Varmawala", explanation: "Abbas and Mastan (the Alibhai Burmawalla brothers) genuinely have a third brother named Hussain — a little-known fact even in the industry. Azeem was option D as a joke." },
      { name: "Chess Prodigy", question: "Someone famously beat Viswanathan Anand in a charity chess stream and is very opinionated. What action did he claim was something only an idiot would do?", options: ["Cheat in a charity chess stream", "Start a podcast", "Call corruption a good thing", "Do an MBA"], answer: "Do an MBA", explanation: "He stated that doing an MBA is something only an idiot would do. 'Start a podcast' was a tempting wrong answer." },
      { name: "Roadies", question: "Road Transport Minister Nitin Gadkari has faced criticism for his E20 fuel policy. Who is the visionary behind this historic move?", options: ["Vikram Sarabhai", "APJ Abdul Kalam", "Steve Jobs", "Shri Nitin Gadkari Ji"], answer: "Shri Nitin Gadkari Ji", explanation: "The E20 ethanol-blending policy is Nitin Gadkari's initiative. The original critical question was softened mid-show after the host got nervous." },
      { name: "Popular Opinion", question: "What is the most irrelevant thing in the world right now?", options: ["Govinda", "Print media", "Khamba's YouTube channel", "Congress Party"], answer: "Congress Party ad in print media", explanation: "The accepted answer was 'Congress Party ad in print media' — combining two of the most irrelevant things into one catastrophically useless object." },
      { name: "Mutual Funds", isTrap: true, question: null, options: [], answer: "+20 — Mutual Funds sahi hai trap", explanation: "Picking 'Mutual Funds' triggered the running 'Mutual Funds sahi hai — subject to market risk' joke and awarded +20 points. No actual question asked." },
    ]
  },

  {
    id: 5, label: "Episode 5", panelists: "Rahul Subramanian · Gaurav Kapoor · Sumaira Sheikh",
    categories: [
      { name: "Make in India", question: "Which of the following is NOT the name of an actual Dongri don?", options: ["Karim Lala", "Mamu Langda", "Tariq Takla", "Moin Totla", "Yusuf Batla", "Shahrukh Khagla"], answer: "Shahrukh Khagla", explanation: "All others (Karim Lala, Mamu Langda, Tariq Takla, Moin Totla, Yusuf Batla) are real Dongri gangster names. Shahrukh Khagla is fabricated." },
      { name: "Toxic Boss", question: "Which of the following is a direct quote from Narayana Murthy?", options: ["First get a life then worry about work-life balance", "How long can you stare at your wife on Sunday, get to office and start working", "Tum saala gulam log hamesha humari jooti ke neeche rahega", "Pao deke maliye kaam pe chaliye"], answer: "How long can you stare at your wife on Sunday, get to office and start working", explanation: "This is Narayana Murthy's actual quote advocating 70-hour work weeks. The 'jooti ke neeche' line is from Lagaan's Captain Russell." },
      { name: "Modiji", question: "Zindagi mein aisi kaun si cheez hai jo hamesha bani rehni chahiye? (What is the one thing in life that should always remain?)", options: ["Majority", "Opposition", "Chai", "Dosti (Friendship)"], answer: "Dosti", explanation: "This question was asked by a Modi lookalike guest on the show. The correct answer was Dosti (friendship). Sumaira answered correctly." },
      { name: "Large Language Model", question: "Fill in the blank: '__ is a cloud, a whisper, a perfect dream… a delicate weightless martial equivalent of a Beethoven symphony, a Husain painting, a Tendulkar century.' What is Shashi Tharoor describing?", options: ["Indian Democracy", "Sanju Samson batting", "Idli", "His deck"], answer: "Idli", explanation: "Shashi Tharoor wrote this elaborate poetic description specifically about idli. He was not wrong — he just could have said 'soft rice cake' instead." },
      { name: "Real Jesus", question: "Which of the following Gautams is the best Gautam?", options: ["Gautam Singhania", "Gautam Adani", "Gautam Gambhir", "Yami Gautam"], answer: "Gautam Adani", explanation: "The intended answer was Gautam Adani — confirmed by the show. Gaurav's reasoning involved stock market appreciation." },
      { name: "Pet Project", question: "Vantara is a privately run wildlife rescue centre in Jamnagar, Gujarat. Which large creature is most commonly associated with it?", options: [], answer: "Elephants", explanation: "Vantara in Jamnagar is most famously known for rescuing and rehabilitating elephants — it was widely in the news for this." },
      { name: "Indian Farmer", question: "A foreign woman in a viral reel misidentified Amitabh Bachchan. What did she falsely assume he did for a living?", options: ["Appear in Panama Papers", "Cure Polio", "Manufacture papad", "Record annoying caller tunes"], answer: "Manufacture papad", explanation: "A viral reel showed Amitabh Bachchan's photo next to a papad brand and the foreign woman mistook the legendary actor for a papad manufacturer." },
      { name: "Sell Out", question: "Which legendary lyricist wrote 'Ping pong paade ka ching, dada hoon, aawara khwabon ka shahzada hoon' for Ching's noodles?", options: ["Prasoon Joshi", "Varun Grover", "Gulzar", "Javed Akhtar"], answer: "Gulzar", explanation: "Gulzar wrote lyrics for the Ching's noodles ad featuring Ranveer Singh. A man can eat." },
      { name: "Shooting Star", question: "In her memoir, Malala Yousafzai mentions a specific activity at Oxford University that brought back the trauma of being shot by the Taliban. What was it?", options: ["Smoking a bong", "Eating Kabuli pulao", "Listening to 'Akhiyon se goli maare'", "Watching 'Four More Shots Please'"], answer: "Smoking a bong", explanation: "Malala wrote that smoking a bong at Oxford brought back the trauma of being shot. The connection is left as an exercise for the reader." },
    ]
  },

  {
    id: 6, label: "Episode 6", panelists: "Kaustubh Agarwal · Ashish Solanki · Rajat Sood",
    categories: [
      { name: "Choose Me", question: "Chalmers University of Technology in Gothenburg, Sweden is one of the world's greatest institutions. Which of these path-breaking technologies was NOT developed there?", options: ["Ultrasound", "Tetra Pak", "Bluetooth", "Facial Recognition", "Asthma Inhaler", "Nicotine Gum", "Dialysis Machine", "Circumcision"], answer: "Circumcision", explanation: "All other technologies (ultrasound, Tetra Pak, Bluetooth, facial recognition, asthma inhaler, nicotine gum, dialysis machine) were genuinely developed at Chalmers. Circumcision predates Swedish engineering." },
      { name: "Indian Parents", isTrap: true, question: null, options: [], answer: "Minus 20 for picking this", explanation: "Rajat picked Indian Parents and immediately lost 20 points with no actual question asked. A trap category." },
      { name: "Military Technology", question: "SONAR was inspired by dolphins. How many vaginas does a dolphin have?", options: [], answer: "1", explanation: "A dolphin has one vagina. Ashish deduced 'ek toh rehti hogi' and was correct." },
      { name: "HR Activity", question: "Which of the following is NOT a real philosophy written behind a rickshaw?", options: ["Nobody remains virgin, life f**ks everyone", "Don't disturb, I am married, I am already very disturbed", "Zara kam pi meri rani, bahut mehnga hai Iraq ka paani", "Kripya horn na bajayein, sarkar ne pehle hi baja rakhi hai"], answer: "Zara kam pi meri rani, bahut mehnga hai Iraq ka paani", explanation: "The Iraq ka paani line is written behind TRUCKS (not rickshaws) — because trucks consume more oil, hence Iraq (oil). Ricksha drivers have different philosophies." },
      { name: "90s Kids", question: "The Tasmanian Devil was inspired by real creatures in Tasmania. How many vaginas does the Tasmanian Devil have?", options: [], answer: "3", explanation: "The Tasmanian Devil has 3 vaginas. Rajat guessed 2 (wrong), Ashish guessed 1 (wrong). The answer is 3." },
      { name: "Shankar Mahadevan", question: "Hospitals reported a rise in respiratory infections in Delhi. What could possibly be the reason?", options: ["Nehru's chain smoking", "Tandoor making too many naans", "Rekha Gupta doing anulom vilom", "Stray dogs farting"], answer: "All of the above", explanation: "Khamba gave all contestants 10 points each — Delhi's air quality is a collaborative multi-source disaster. All were plausible." },
      { name: "Useless Brother", question: "Which of the following has Abhinav Kashyap (Anurag's brother) actually said?", options: ["Main raaste pe aa gaya toh Salman mujhpe gaadi chadha dega", "Kuch bhi bolo Lawrence Bishnoi kaam toh accha hi kar raha hai", "Thappad se dar nahi lagta, podcast se lagta hai", "Vo dil mein bhi aata hai aur samajh mein bhi aata hai, bas jail mein nahi aata"], answer: "Main raaste pe aa gaya toh Salman mujhpe gaadi chadha dega", explanation: "Abhinav Kashyap (director of Dabangg) has publicly said he fears Salman Khan would run him over if he spoke out against him." },
      { name: "Demonetization", question: "What is the best app to sell your old phone with home pickup and instant payment?", options: ["Spotify", "Cashify", "Shopify", "Sanchar Saathi App"], answer: "Cashify", explanation: "Brand integration — Cashify is the episode sponsor. Rajat took -10 first for naming competitor brands, landing at net zero." },
      { name: "Beatles", question: "Paul McCartney was inspired by a blackbird's call in Rishikesh. How many vaginas does a blackbird have?", options: [], answer: "0 (birds have a cloaca, not a vagina)", explanation: "Birds have a single opening called a cloaca — not classified as a vagina. Ashish guessed 1 (wrong). The answer is 0/cloaca." },
    ]
  },

  {
    id: 7, label: "Episode 7", panelists: "Anubhav Singh Bassi · Aakash Gupta · Shreeja Chaturvedi",
    categories: [
      { name: "Below Poverty Line", question: "BPL also refers to the Bangladesh Premier League. Which of these bizarre events did NOT happen in the BPL?", options: ["Match fixing", "Players boycotting due to bounced cheques", "Scarcity of cricket balls during practice", "Could not afford Hawk-Eye review", "Bus driver refused to return players' kit bags as he wasn't paid", "Being grateful to India for helping them get independence"], answer: "Being grateful to India for helping them get independence", explanation: "All other events (match fixing, bounced cheques, ball scarcity, no Hawk-Eye, kit bag hostage) actually happened in the BPL. Bangladesh gratitude to India has not." },
      { name: "Comics Winner", isTrap: true, question: "Aashish Solanki is a Comicstaan winner and the brain behind 'Judge Me If You Can.' Which visionary brand is supporting new panel shows for the audience's enjoyment?", options: [], answer: "Cashify — brand integration, everyone got 10 points", explanation: "A Cashify brand integration disguised as a question. All contestants got 10 points for it." },
      { name: "Crazy Ex", question: "Pakistan's Defence Minister recently made a tall claim about the IMF. What did he say?", options: ["Friendship over with IMF, China is my new best friend", "Pakistan may not need loans after six months", "Bob's the king, mera ghante ka game", "My pledge is that I will be a pilot and save Pakistan"], answer: "Pakistan may not need loans after six months", explanation: "Pakistan's Defence Minister actually claimed this. Pakistan has since needed more IMF loans. The imagination required." },
      { name: "Delhi MMS", question: "Which of the following is a direct quote from Manmohan Singh?", options: ["Criticism is the soul of democracy", "History will be kinder to me", "Keh do na, you are my Sonia", "Tussi ja rahe ho, tussi na jao", "Punjabi aa gaye", "Nit controversy te create milgi"], answer: "History will be kinder to me", explanation: "Manmohan Singh famously said 'History will be kinder to me' in response to criticism of his UPA tenure. History is still deliberating." },
      { name: "Male Feminist", question: "Which of the following was the most unrealistic thing in the film Animal?", options: ["A pilot having sex while flying the plane", "A group of Sardars going to UK and still coming back", "Everyone understanding what Rashmika was saying", "Ranbir sleeping with only two women"], answer: "Ranbir sleeping with only two women", explanation: "Given the film's hypermasculine excess, Ranbir's character sleeping with only two women was considered the most unrealistic element." },
      { name: "PDA (Prayagraj Dev. Authority)", question: "Which of these actually happened at the Prayagraj Development Authority?", options: ["Offering ₹1650 per head for catching monkeys", "Beating up an Anti-Corruption officer", "Charging ₹500 fee for organising a protest", "Refusing a name-change application for Gandwa Gaon", "Accused of giving only one laddoo instead of two for Independence Day"], answer: "Beating up an Anti-Corruption officer", explanation: "The Anti-Corruption Bureau caught PDA officials taking a bribe — and the PDA officials beat up the officer who came to catch them. A bold strategy." },
      { name: "Only Fans", question: "Which of these has NOT happened in Udit Narayan's life?", options: ["Was compared to Asaram Bapu", "Lead actor in Nepal's highest-grossing film", "Sang in court to convince wife to drop a complaint", "Sang in a Hollywood film"], answer: "Sang in court to convince wife to drop a complaint", explanation: "This happened to a different case, not Udit Narayan. He has been compared to Asaram Bapu, starred in Nepal's highest-grossing film for 16 years, and sung in a Hollywood film." },
      { name: "Indian PM", question: "Comedian Pranit More was attacked by a mob for cracking jokes on Veer Pahadiya. Which of the following jokes should he avoid?", options: ["Knock knock. Who's there? Veer Pahadiya hoon.", "Difference between Veer Das and Veer Pahadiya: only one has a future in Bollywood.", "Why did Veer Pahadiya cross the road? To check if there were fans.", "All of them."], answer: "All of them", explanation: "Bassi's witty answer was 'do all of them' — meaning Pranit should avoid every joke on that list to stay safe from the fanbase." },
    ]
  },

  {
    id: 8, label: "Episode 8", panelists: "Hoezaay · Urooj Ashfaq · Rahul Subramanian",
    categories: [
      { name: "Ancient Weapons", question: "Dhanush made his Hindi debut with Raanjhanaa. Which punchline did comedy legend Sunil Pal bring to life inspired by the film?", options: ["Raanjhana mein hai Sonam, Kerala mein manate hain Onam", "Mere pyaare Raanjhana, bartan saare maanjhna", "Raanjhana hua hai tera, Salman ke saath hai Shera", "Raanjhana se door bhaago kyunki is picture ka naam hai Raanjhana Raanjhana Raanjhana"], answer: "Mere pyaare Raanjhana, bartan saare maanjhna", explanation: "Sunil Pal's famous punchline — 'My dear Raanjhana, all the dishes need washing' — a play on the film title as a domestic chore pun." },
      { name: "PC Upgrade", isTrap: true, question: "Which seven-letter future unicorn app starting with C is the best way to upgrade your phone?", options: [], answer: "Cashify — brand integration trap", explanation: "Hoezaay picked this knowing it would be a brand question. The answer was Cashify, the episode sponsor." },
      { name: "Punchable Face", question: "Which of the following is NOT a real controversy around Shakib Al Hasan?", options: ["Named in a murder case", "Quit his team over the phone", "Made a controversial gesture on live TV", "Slapped a fan", "Obsessively spoke about lendoo with Suresh Raina"], answer: "Obsessively spoke about lendoo with Suresh Raina", explanation: "Shakib has genuinely been named in a murder case, quit his team over the phone, made a live TV gesture, and slapped a fan. The Raina/lendoo story is fabricated." },
      { name: "Dosti Bani Rahe", question: "Which of these is a real tagline used by the Adani Group of Companies?", options: ["Modi hai toh mumkin hai", "Money hai toh honey hai", "Marunga sar pe, hagega ghar pe", "Hum karke dikhate hain", "Tedha hai par mera hai", "Don ko pakadna mushkil hi nahi, namumkin hai"], answer: "Hum karke dikhate hain", explanation: "'Hum karke dikhate hain' (We show by doing) is the actual Adani Group tagline. The others are government slogans, Bollywood dialogue, or noise." },
      { name: "Famous Warriors", question: "Which of the following is NOT a real part of Star Wars?", options: ["Force Rising", "Hand Solo", "Star Horse Princess Leia", "Obi Wan Can Blow Me"], answer: "Obi Wan Can Blow Me", explanation: "Force Rising (The Force Awakens), Hand Solo (Han Solo), Star Horse Princess Leia are all real references. 'Obi Wan Can Blow Me' is fabricated." },
      { name: "The Rebel Kid", question: "Umar Khalid has been in jail for almost half a decade. Which college did he go to?", options: [], answer: "JNU (Jawaharlal Nehru University)", explanation: "Umar Khalid studied at JNU. Urooj answered immediately — earning a jokey -20 penalty threat from Khamba for 'anti-national activity of knowing this'." },
      { name: "Aunty Number One", question: "What did Nita Ambani dress up as at her Jamnagar Halloween party?", options: [], answer: "Audrey Hepburn", explanation: "Nita Ambani dressed as Audrey Hepburn. Wrong guesses included Deadpool, Wonder Woman, Catwoman, Captain America before Urooj got it right." },
      { name: "Jurassic Park", question: "Which of the following songs was picturised on Dino Morea?", options: ["In Dino dil mera", "Char dinon ka pyaar o rabba, lambi judaai", "Morya re Morya re", "Ye sheher hai Aman ka, yahan ki fizaayein nirali"], answer: "Char dinon ka pyaar o rabba, lambi judaai", explanation: "The song 'Char dinon ka pyaar o rabba, lambi judaai' was picturised on Dino Morea. Hoezaay answered correctly without needing any reason." },
      { name: "Veer Pahadiya", question: "A viral 2019 photograph of Mount Everest highlighted a surprising problem faced by climbers. What was it?", options: ["Global vomit", "Open defecation", "Garbage everywhere", "Traffic jams", "Delhi guys", "Power cuts"], answer: "Traffic jams", explanation: "The 2019 viral Everest photo showed a massive queue of climbers near the summit — essentially a traffic jam at 8,000 metres." },
    ]
  },

  {
    id: 9, label: "Episode 9", panelists: "Anirban Dasgupta · Biswajit Sarkar · Prashasti Singh",
    categories: [
      { name: "Beef", question: "Which of the following is the biggest beef right now?", options: ["Arjun Kapoor and Instagram", "Kunal Kamra and startup founders", "Gautam Gambhir and winning home Test series", "Anil Dasgupta and Rohan Desai", "Modi and press conference"], answer: "Modi and press conference", explanation: "Modi has never held a formal press conference as Prime Minister — the longest-running beef in the country." },
      { name: "Nepotism", question: "Who is Ibrahim Ali Khan's real mother?", options: [], answer: "Amrita Singh", explanation: "Ibrahim Ali Khan is the son of Saif Ali Khan and Amrita Singh — his biological mother. Gauri Khan is his stepmother." },
      { name: "Sonam Bewafa Hai", question: "Sonam Wangchuk was arrested under the National Security Act. What was the charge?", options: ["Claiming Linkin Park's 'So Long' is about him", "Criticising the film Dhurrandar", "Using a vacuum cleaner to deliver a baby on campus", "Plotting a violent revolt against the government"], answer: "Plotting a violent revolt against the government", explanation: "Sonam Wangchuk was charged with plotting violent revolt under the NSA — widely seen as an excessive charge for a peaceful environmental activist." },
      { name: "Call From Mother", isTrap: true, question: null, options: [], answer: "+22 for picking — others get -22 for NOT picking", explanation: "Whoever picked 'Call From Mother' got +22 points. The other contestants who didn't pick it lost 22 points each. Anirban picked it wisely." },
      { name: "IIT Comedian from Odisha", question: "One of TVF's most popular shows follows a young protagonist studying hard to clear an entrance exam. What show?", options: ["Kota Factory", "Panchayat", "Aspirants", "Half CA"], answer: "Kota Factory", explanation: "Kota Factory follows a student trying to crack IIT-JEE — directly matching the description. Biswa Kalyan Rath was a writer at TVF." },
      { name: "Fir Se Ud Chala", question: "Vijay Mallya bought a historic Indian artefact at Harrods using money saved by not paying Kingfisher employees. What did he buy?", options: ["A middle finger for RBI", "A two-hour podcast episode", "Gandhi's glasses", "Tipu Sultan's sword", "Modi's degrees", "Frequent flyer points"], answer: "Tipu Sultan's sword", explanation: "Mallya bought Tipu Sultan's sword at Harrods in 2016. It disappeared for 6 years, reappeared at auction in 2023, and he sold it for 10x the price." },
      { name: "Gayi Padosan", question: "Sheikh Hasina's house was stormed by protesters in 2024. Which item was NOT stolen?", options: ["Raw fish", "A blouse", "Three suitcases", "Rice cooker", "Chicken korma", "iPhone 16 128GB"], answer: "iPhone 16 128GB", explanation: "Raw fish, clothing, suitcases, rice cooker, and chicken korma were all stolen. The iPhone 16 was not among the reported items." },
      { name: "Char Bottle Vodka", question: "Which Ravi Shastri quote went viral after India's Test win in Australia?", options: ["Ganpat chal daru la", "I only believe in Jersey bhai", "Thodi der ke liye gote munh mein the", "I got 99 problems and the pitch ain't one"], answer: "Thodi der ke liye gote munh mein the", explanation: "Ravi Shastri's quote on live TV — 'for a while things were in the mouth' — went viral for its glorious unintentional double entendre." },
      { name: "Do Bhai Dono Tabaahi", panelSpecific: true, question: "Between Khamba and Rohan Desai, which disease have they NOT collectively suffered from?", options: ["Kidney stones", "Tuberculosis", "Pancreatitis", "Hepatitis A", "Cancer", "Testicular torsion", "Piles"], answer: "Piles", explanation: "Between them they've had kidney stones, TB, pancreatitis, hepatitis A, cancer, and testicular torsion — but not piles. Yet." },
    ]
  },

  {
    id: 10, label: "Episode 10", panelists: "Ashish Solanki · Shreya Priya Roy · Omkar Yadav",
    categories: [
      { name: "Garbage", isTrap: true, question: null, options: [], answer: "+20 just for picking this", explanation: "Very few people in India pick up garbage. Congratulations for supporting Swachh Bharat Abhiyan — +20 points, no question asked." },
      { name: "Sleeping Beauty", question: "Which of the following is NOT on the ECI's free election symbol list?", options: ["Baby walker", "Road roller", "Lacy frock", "Noodle ball", "Nail cutter", "Extension board"], answer: "Road roller", explanation: "Road roller was withdrawn from the ECI free symbol list around 2015-16 for being 'too aggressive'. Baby walker, lacy frock, noodle ball, nail cutter, and extension board remain valid symbols." },
      { name: "Things Naazi Se", question: "Which of the following is a real BYJU's sales tactic?", options: ["Pushing loans on low-income parents without consent", "Shaming parents into buying products", "Tracking free accounts to guilt-trip parents", "Refusing cancellations and refunds", "Falsely claiming an 8-year-old student earned millions", "All of the above"], answer: "All of the above", explanation: "BYJU's was documented using every single one of these tactics. The company went bankrupt in 2024." },
      { name: "Lern University", question: "Which of the following is an actual research patent by Galgotias University?", options: ["Internet at breakneck speed — a reality", "Strategic appropriation of foreign IP — a robot dog", "Satellite image reader to track minorities — a necessity", "System and method to control devices through mental activities — a thesis"], answer: "System and method to control devices through mental activities — a thesis", explanation: "This is a genuine Galgotias University patent. They filed more patents than all IITs combined in 2022-23." },
      { name: "Furniture", isTrap: true, question: "Which of the following provides the most comfort?", options: ["Watching T20 Finals knowing ICC Chairman is Jay Shah", "Knowing your father is rich after you've run over someone", "Making panel shows knowing famous comics will just show up", "Not firing Rohan and Aman knowing AI will replace them", "Men's premium innerwear by Damensch"], answer: "Damensch — brand integration answer", explanation: "A Damensch brand integration disguised as a comfort question. The entire setup leads to the sponsor." },
      { name: "Feku", question: "What real question did the MC ask Neeraj Chopra and his wife at their wedding reception?", options: ["Aapke yahan bachpan mein nahi ho jaata ye sab?", "Thoda aur north mein paida hote toh javelin ne kuch aur phenk rahe hote", "Ladai ke time kya aap ek dusre pe cheezein phenkte ho?", "Waise aapka javelin kitna lamba hai?"], answer: "Ladai ke time kya aap ek dusre pe cheezein phenkte ho?", explanation: "The wedding MC actually asked if they throw things at each other during fights — a playful javelin reference that became a viral moment from the reception." },
      { name: "Naam Bade Darshan Chote", question: "Post his recent arrest, Rajpal Yadav noticed areas of improvement in the Indian prison system. What did he say should be added to jails?", options: ["Welcome drink", "Live dosa counter", "Early check-in, late check-out", "Height-wise line for lunch and dinner", "Waiting lounge for execution", "Special smoking zones"], answer: "Special smoking zones", explanation: "Rajpal Yadav publicly demanded special smoking zones in jails post-arrest. A celebrity's first prison reform thought." },
      { name: "Fat Boy Slim", question: "Adnan Sami became an Indian citizen in 2016. Which of the following has he genuinely done to prove loyalty to India?", options: ["Called for renaming Mysore Park to 'Mysore Shri'", "Killed a chicken because it was doing 'park park pak'", "Told AR Rahman to go back to Pakistan", "When asked why not celebrating 14th August, replied 'I will do it tomorrow'"], answer: "When asked why not celebrating 14th August, replied 'I will do it tomorrow'", explanation: "Adnan Sami replied he'd celebrate Pakistan's Independence Day the next day — i.e., on 15th August, India's Independence Day. The most Indian response possible." },
    ]
  },

  {
    id: 11, label: "Episode 11", panelists: "Gurleen Pannu · Rahul Dua · Gaurav Gupta",
    categories: [
      { name: "Bhabhi Ji Ghar Pe Hai", question: "What contribution are Punjabis making in Italy?", options: ["Providing arms to the Italian mafia", "Helping people lose weight through bhangra classes", "Helping rear cows for the cheese production industry", "Reviving the wine industry by drinking too much"], answer: "Helping rear cows for the cheese production industry", explanation: "Punjabis in Italy are working as cattle herders for the dairy and cheese industry — a direct import of Punjab's agricultural DNA." },
      { name: "Thar Drivers", question: "According to the American Society of Plastic Surgeons, what is the most popular cosmetic surgery among men?", options: [], answer: "Gynecomastia surgery (male breast reduction)", explanation: "Male breast tissue reduction is the top cosmetic surgery for men globally. Nobody on the panel guessed this." },
      { name: "Drive to Survive", question: "Which hashtag did Rishabh Pant use in his viral response to Urvashi Rautela?", options: ["#TakeItEasyUrvashi", "#MeraPicchaChhodoBehen", "#AajaMeriGaadimeinBaithJa", "#ZindaHoonYaarKafiHai", "#OStreeKalAana"], answer: "#MeraPicchaChhodoBehen", explanation: "Pant's post called out people who lie in interviews for meager popularity and ended with #MeraPicchaChhodoBehen (Leave me alone, sister)." },
      { name: "Tumse Na Ho Payega", question: "Rahul Gandhi's YouTube channel comments were flooded with congratulations. What achievement were they celebrating?", options: ["Completing 10,000 steps", "Meeting half the criteria of being a Baaziger", "Crossing 10 million YouTube subscribers", "Getting through a speech without becoming a meme", "Finally being invited on Kunal Kamra's Khabreaam", "Getting one year closer to ending this farce"], answer: "Crossing 10 million YouTube subscribers", explanation: "Rahul Gandhi's channel hit 10 million subscribers. His supporters celebrated. The channel quality remains a topic of debate." },
      { name: "Indian Army", question: "Who was the best host of Shark Tank India?", options: ["Ranvijay Singh", "Ashish Solanki", "Sahiba Bali", "Kullu"], answer: "All of the above", explanation: "The show gave 'all of the above' — a diplomatic answer celebrating every host. Rahul Dua had previously hosted Shark Tank India." },
      { name: "Sell Out", panelSpecific: true, question: "Since Khamba's viral clip about comics selling out with brand work, which of these has HE done?", options: ["Instagram reel for Mogu Mogu", "Read WOW Skincare features on stage", "Used podcast with wife to promote Pond's", "Bought smartwatch for wife to promote boAt on Valentine's", "Put a minute-long ad in Episode 8 to promote Cashify"], answer: "All of the above", explanation: "He did all five brand integrations despite his earlier principled stance. He acknowledges this completely." },
      { name: "Sardar Patel", question: "According to new US State Department guidelines, which is now valid grounds for rejecting a US visa?", options: ["Pronouncing Trump's name as 'Donald'", "Asking a female visa officer to show 'bob and vagene'", "Being too fat", "Calling Kamala's campaign 'Kamala Ka Hamla'"], answer: "Being too fat", explanation: "The US now considers obesity as grounds for visa rejection, arguing obese immigrants may burden the healthcare system." },
      { name: "Silence of the Lamps", question: "During the China boycott after the Galwan clash, which of these did NOT happen?", options: ["Man threw Chinese TV out of window", "Protesters burned Kim Jong-un effigy thinking he was Chinese", "Delhi's Defence Colony declared war on China", "Taking away Meiyang Chang's film roles"], answer: "Taking away Meiyang Chang's film roles", explanation: "The TV toss, Kim Jong-un effigy burning, and Defence Colony LOC all actually happened. Meiyang Chang's film roles were not affected." },
      { name: "Aai Am the Best", isTrap: true, question: null, options: [], answer: "Minus 20 for picking this", explanation: "Picking 'I Am The Best' costs -20 points immediately. Modi Ji is the best, not you." },
    ]
  },

  {
    id: 12, label: "Episode 12", panelists: "Shamik Chakrabarti · Chirag Panjwani · Shreeja Chaturvedi",
    categories: [
      { name: "Do Not Pick", isTrap: true, question: null, options: [], answer: "A forward/back maze with no real question or points", explanation: "Chirag picked this rebelliously. It turned into a maze of 'go forward or go back' prompts with no actual trivia question." },
      { name: "Tukde-Tukde Gang", question: "Before settling on the India-Pakistan partition, what was Mountbatten's original plan?", options: ["Nehru ke bakkad bakkad Bombay bo bo", "Divide into 10 Premier League teams", "Divide into 500+ provinces", "Divide into SRK, Salman, and Aamir fans"], answer: "Divide into 500+ provinces", explanation: "Mountbatten's original plan was to divide the subcontinent into over 500 princely states — before settling on the two-nation partition." },
      { name: "That 70s Show", question: "Which of the following did NOT happen during Indira Gandhi's Emergency?", options: ["Using government machinery to intimidate opposition", "Censoring media from criticising government", "Jailing students and protesters", "Tightening censorship laws over artists", "Forcing actors to lip-sync 'Indira hai toh India hai'"], answer: "Forcing actors to lip-sync 'Indira hai toh India hai'", explanation: "A, B, C, D all happened during the 1975–77 Emergency. The forced lip-sync mandate for actors was fabricated." },
      { name: "True Caller", question: "What unlikely business model have gangsters like Lawrence Bishnoi adopted?", options: ["Shooting outside cafes", "Forcing musicians to upload videos on gangsters' YouTube channels", "Starting their own OnlyFans accounts", "Human trafficking as bhangra bookings", "IAS coaching centres"], answer: "Forcing musicians to upload videos on gangsters' YouTube channels", explanation: "Gangsters have been directing musicians to upload their music on the gangsters' own YouTube channels to earn ad revenue — a surprisingly modern business model." },
      { name: "Stand Up Comedy", isTrap: true, question: "Courts are where we see many trials. Which of these is the greatest trial in history?", options: ["Akshay Kumar trial in Haidraa", "Akshay Kumar trial in Rustom", "Akshay Kumar trial in Kesari 2", "Akshay Kumar trial in OMG 1 and 2", "Akshay Kumar trial in Jolly LLB 2 and 3", "Damensch free 30-day trial for premium members"], answer: "Damensch 30-day free trial — brand integration", explanation: "All options were Akshay Kumar courtroom films until the sponsor's free trial appeared as option F. A Damensch brand integration dressed as trivia." },
      { name: "No Country for Old Men", question: "What was LK Advani's profession in the 1960s before politics?", options: ["Professional rath driver", "Professional film critic", "Professional PM wannabe", "Professional building demolition expert", "Amateur hair model", "Lead actor of RK Laxman's Common Man biopics"], answer: "Professional film critic", explanation: "LK Advani was a film enthusiast who wrote movie reviews for magazines in the 1960s — a little-known fact about the BJP veteran." },
      { name: "Star of David", question: "Which of the following has NOT happened in Govinda's life?", options: ["Paid ₹5 lakh for slapping a fan", "Charged a dozen bananas and a coconut for acting in a film", "Shot himself in the foot", "Rejected a role in James Cameron's Avatar saying not his vibe", "His duplicate performed to 15,000 when he didn't show up", "Threatened Karan Johar in Rajinikanth style", "Launched his own OTT platform called Filmi Lattu"], answer: "His duplicate performed to a crowd of 15,000 when he failed to show up", explanation: "All other incidents are on record. The duplicate performance story was the fabricated option." },
      { name: "Tiger Shroff", question: "The astrologer who predicted Nepal's Gen-Z protests (2023) also predicted which of the following?", options: ["Kejriwal will be released from prison", "India's Got Latent will return for Season 2", "Prithviraj will never make a comeback", "Nobody will understand what 'six-seven' means", "Aman will get a laptop"], answer: "Prithviraj will never make a comeback", explanation: "The same astrologer who called Nepal's protests and India's energy crisis also predicted that Prithviraj Sukumaran would never make a career comeback." },
      { name: "White Woman", question: "In which of the following films did Rakhi Gulzar NOT play a widow?", options: ["Karan Arjun", "Ram Lakhan", "Border", "Baazigar", "Dacait", "Jeevan Mrityu", "Ek Sangharsh", "Soldier", "Hamare Tumhare", "Rudaali", "Anari", "Tapasya", "Phool Aur Kaante"], answer: "Tapasya", explanation: "Tapasya (1976) is the only film where Rakhi was not married — so she could not be widowed. She won the Filmfare Best Actress for it." },
    ]
  },

  {
    id: 13, label: "Season Finale", panelists: "Abish Mathew · Kaneez Surka · Rohan Joshi",
    categories: [
      { name: "Mother", isTrap: true, question: null, options: [], answer: "Minus 20 for picking this", explanation: "Rohan picked 'Mother' expecting a real question and immediately got -20 points. Some categories are traps." },
      { name: "Modi Ji", isTrap: true, question: "Which iconic Indian company has a German name and is known for making the most comfortable innerwear for men?", options: ["Jockey", "Damensch", "Lux Cozi", "Rupa"], answer: "Damensch — brand integration", explanation: "The entire question was a convoluted word-association chain (Nirav Modi → UK → Uttarakhand → Bhumi Pednekar → Ayushmann → German automobile → Damensch) purely as a sponsor plug." },
      { name: "Home Alone", question: "When Omar Abdullah was released from house arrest and COVID lockdown was announced the same day, which meme did he share on Twitter?", options: [], answer: "A meme about being locked down again immediately after getting out", explanation: "Omar went from political house arrest directly into national COVID lockdown. He shared a meme capturing the irony. Perfect timing by the universe." },
      { name: "Mia Khalifa", question: "When the Burj Khalifa opened in 2010, trucks queued every night to take something away. What?", options: ["Poop", "Escorts", "Pet camels", "Empty champagne bottles", "Influencers shouting 'Habibi come to Dubai'", "Your hopes of ever affording a place there"], answer: "Poop", explanation: "The Burj Khalifa wasn't connected to city sewage when it opened. Poop trucks came every night. This is also the origin of the 'Dubai chocolate' meme." },
      { name: "AIB", question: "What is the Aeronautical Institute of Bangladesh (AIB)'s crowning achievement?", options: ["Got Sheikh Hasina business class tickets while escaping", "Airdropped fake Aadhaar cards through paper planes", "Attacked Mannat after Mustafizur was kicked out of a team", "Only private aviation institute approved by Civil Aviation Authority of Bangladesh"], answer: "Only private aviation institute approved by Civil Aviation Authority of Bangladesh", explanation: "AIB's actual achievement is simply being the only CAAB-approved private aviation training institute in Bangladesh. The other options were entertaining distractions." },
      { name: "Barbecue Nation", question: "During the 2026 Iran-Israel conflict, which of the following did NOT happen?", options: ["Tourists left 1-star reviews after a Dubai hotel was attacked", "Pakistan PM tweeted 'I condom' instead of 'I condemn'", "Qatar evacuated 147 show horses", "US aircraft carrier overflowed with poop"], answer: "Pakistan PM tweeted 'I condom'", explanation: "The Dubai hotel 1-star reviews, 147 Qatar show horses, and the aircraft carrier poop overflow all reportedly happened. The PM typo was fabricated." },
      { name: "Mera Number One", question: "Morarji Desai once accidentally revealed crucial information to Pakistani General Zia-ul-Haq. What did he spill?", options: ["Batting order of Indian cricket team", "That Dharam 1 was better than Dharam 2", "Listens to Pakistani Coke Studio on incognito", "That India knew about Pakistan's nuclear site at Kahuta", "That Rekha and Amitabh were together"], answer: "That India knew about Pakistan's nuclear site at Kahuta", explanation: "Morarji Desai revealed to Zia-ul-Haq that Indian intelligence knew about Pakistan's secret nuclear facility at Kahuta — a significant intelligence blunder." },
      { name: "Yeh Toh Tatti Hai", question: "Companies have been hiring improv comedy actors for a very specific task. What task?", options: [], answer: "To train AI on human emotion", explanation: "Tech companies are using improv actors' natural emotional range to create AI training data for human emotion modelling. Comedy is now infrastructure." },
      { name: "Choti Bachi Ho Kya", question: "When Jeffrey Epstein texted Anil Ambani offering a 'tall Swedish blonde' in 2017, how long did Anil take to reply 'Arrange that'?", options: [], answer: "20 seconds", explanation: "Anil Ambani reportedly replied within 20 seconds — an essentially immediate response with no deliberation whatsoever." },
    ]
  }
]
