export const PICKME_EPISODES = [
  {
    id: 1, label: "Episode 1", panelists: "Hoezay · K Sebastian · Abhish Mathew",
    categories: [
      { name: "How Can She Slap?", question: "Nothing matches the prolific slap-taking ability of ex-Delhi CM Arvind Kejriwal. Which of the following did NOT happen?", options: ["Slapped in 2014", "Slapped in 2016", "Slapped in 2019", "Slapped with ED and corruption charges"], answer: "Slapped in 2016", explanation: "In 2016 it was ink that was thrown at him, not a slap. The 2014 and 2019 incidents were actual physical slaps." },
      { name: "AIB", question: "Which of the following AIB members is the funniest?", options: ["Tanmay Bhat", "Gursimran Khamba", "Rohan Joshi", "Ashish Shakya"], answer: "Tanmay Bhat", explanation: "Khamba declared Tanmay the funniest — a joke-writing machine who has done the most stand-up. Also funny because Khamba himself is one of the options." },
      { name: "Indian Culture", question: null, options: [], answer: "Minus 20 just for picking this", explanation: "Picking 'Indian Culture' triggered an instant -20 penalty. How dare you question Indian Culture.", isTrap: true },
      { name: "Baking Accident", question: "In front of which bakery in Bandra did the Salman Khan hit-and-run incident allegedly occur?", options: ["A1 Bakery", "American Express Bakery", "J Harsh & Co", "Hit and Run Bakery"], answer: "American Express Bakery", explanation: "The 2002 incident took place outside American Express Bakery on Bandra's Hill Road." },
      { name: "Children's Books", question: "Which of the following is a real Harry Potter adult parody film?", options: ["Harry Potter and the Gobbling of Cock", "Harry Potter and the Philosopher's Bone", "Hairy Cocker and the Deathly Holes", "Hori Potter and the Soft Balls"], answer: "Hori Potter and the Soft Balls", explanation: "Also available in 3D. The other options are too lazy — porn workers actually put in effort." },
      { name: "Useless Brothers", question: "After declaring bankruptcy in 2020, what percentage of ₹47,251 crore debt was Anil Ambani asked to repay by NCLT in 2023?", options: [], answer: "0.92%", explanation: "Despite owing ₹47,251 crore, only 0.92% was demanded. The limit to success truly is imagination." },
      { name: "21st Century Poets", question: "Yo Yo Honey Singh notoriously rhymed a body organ with a popular Indian fried snack. What snack?", options: [], answer: "Pakoda", explanation: "Honey Singh rhymed a male body part with pakoda. This is what Spotify hides from you." },
      { name: "Modi Ji", question: "What is the name of the plus-sized doctor character in Taarak Mehta Ka Ooltah Chashmah?", options: [], answer: "Dr. Haathi", explanation: "His wife is also called Komal Haathi. The show preaches inclusivity — and then names its characters 'Elephant'." },
      { name: "Punchable Face", question: "Ranveer Allahbadia (BeerBiceps) is known for asking a wide variety of questions. Which of the following has he NOT asked?", options: ["Aapko khaana pasand hai?", "Are Punjabi people in the Illuminati?", "Would you rather [redacted for legal reasons]", "If a woman has sex, is it like she loses some energy?"], answer: "Are Punjabi people in the Illuminati?", explanation: "Options A, C, and D are real questions from his podcasts. The Illuminati one was the fake. We think." },
    ]
  },
  {
    id: 2, label: "Episode 2", panelists: "Karunesh Talwar · Anirban Das · Shamik Chakravarti",
    categories: [
      { name: "AIB", question: "AIB — Afghanistan International Bank — is the largest bank in Afghanistan. Who of the following is NOT in AIB management?", options: ["Rami Yousefi", "Abdullah Abdullah", "Michael Cunningham", "Lalit Kumar Jha"], answer: "Abdullah Abdullah", explanation: "Abdullah Abdullah is a former Foreign Affairs Minister of Afghanistan — a politician, not a banker. Classic bait-and-switch." },
      { name: "Bong Ki Baat", question: "Which of the following is NOT a real Mamata Banerjee quote?", options: ["Ka Ka Ji", "Aap rock leke khada hoga, hum kuchush kuchush karke usko kaat denge", "Cashless ke naam pe baseless ho gaya aur faceless ho gaya", "Shobba khair abba khair Joy Bangla"], answer: "Shobba khair abba khair Joy Bangla", explanation: "The other three are real (or real enough). The last one just sounds Bengali enough to be believable — it is not." },
      { name: "Salman Bhai", question: "The Satanic Verses returned to Indian bookstores after a 36-year ban. Why did the ban lapse?", options: [], answer: "The government could not find the original ban order document", explanation: "Bureaucracy at its finest — they simply misplaced the original ban order and couldn't renew it. Salman Rushdie is free by accident." },
      { name: "Mughal Dynasty", question: "Along with having a son named Taimur, what was the worst thing that happened to Saif Ali Khan in 2025?", options: ["Bhopal Palace declared enemy property", "Getting stabbed by an intruder", "Ibrahim Ali Khan acting", "Sara Ali Khan in Metro In Dino"], answer: "Getting stabbed by an intruder", explanation: "Saif Ali Khan was actually stabbed at his Mumbai home in early 2025. Objectively the worst thing on the list." },
      { name: "Mads of Bollywood", question: "Who is Kangana Ranaut talking about in this quote: 'O chamcha, chal tu jinki chaat chaat ke kaam leta hai na, main unki roz bajati hoon, zyada mat uchal'?", options: ["Hrithik Roshan", "Diljit Dosanjh", "Rajeev Masand", "People of Manali"], answer: "Diljit Dosanjh", explanation: "Directed at Diljit during the farmers' protest era when he was standing up for Punjabi rights. Kangana disagreed." },
      { name: "PM Modi", question: null, options: [], answer: "Minus 24 just for picking this", explanation: "How dare you question him. Minus 24 points. No question asked.", isTrap: true },
      { name: "Man's Best Friend", question: "What breed of dog does the right-wing ecosystem call Dhruv Rathee?", options: ["Pomeranian", "French Poodle", "German Shepherd", "Shih Tzu"], answer: "German Shepherd", explanation: "He lives in Germany, hence 'German Shepherd' — implying he does the bidding of foreign masters. Rathee is not amused." },
      { name: "Higher Education", question: "Which of the following is the odd one out and why? IIT-JEE, UPSC, CA, NEET.", options: ["IIT-JEE", "UPSC", "CA", "NEET"], answer: "NEET", explanation: "NEET is the only exam TVF has not yet made a web series about. Kota Factory, Aspirants, Half CA all exist. NEET is still waiting." },
      { name: "Korean Music", question: "Which of the following songs is an ORIGINAL composition by Pritam?", options: ["Badtameez Dil", "Zara Zara Touch Me", "Bhool Bhulaiyaa title track", "Channa Mereya"], answer: "Channa Mereya", explanation: "Pritam originally composed Channa Mereya for Bajrangi Bhaijaan, Salman didn't like it, then it went to Ae Dil Hai Mushkil and became massive. The others are largely 'inspired' compositions." },
    ]
  },
  {
    id: 3, label: "Episode 3", panelists: "Raunak Rajani · Gurleen Pannu · Amit Tandon",
    categories: [
      { name: "Civil Engineering", question: "Which Bollywood singer's songs were found on Osama Bin Laden's hard drive?", options: [], answer: "Alka Yagnik", explanation: "When the US raided the compound, Alka Yagnik's songs were on his hard drive. She reportedly said 'shayad Osama ke andar bhi ek chhota sa kalakar tha'." },
      { name: "Modi Ji", question: "Modi Ji was seen at a lavish UK party singing a song with fugitive Vijay Mallya. What song?", options: ["Oops I Did It Again", "I Did It My Way", "Apna Sapna Money Money", "Fatela Jeb Fill Jayega"], answer: "I Did It My Way", explanation: "Vijay Mallya, a fugitive living in the UK who appears on podcasts, would naturally anthem himself to Sinatra's 'I Did It My Way'." },
      { name: "Oscar Snubs", question: "Which of the following is NOT a real Bhojpuri film?", options: ["Gamchha Wala I Love You", "Biwi Tumhari Bachche Hamare", "Dulhan Chahiye Pakistani Role"], answer: "Gamchha Wala I Love You", explanation: "The real one is 'Riksha Wala I Love You'. The other two ('Biwi Tumhari Bachche Hamare' and 'Dulhan Chahiye Pakistani Role') are painfully real Bhojpuri films." },
      { name: "Arts", question: null, options: [], answer: "Minus 20 for picking Arts", explanation: "Picking Arts automatically deducts 20 points. This is a joke about life choices. You should have done Science.", isTrap: true },
      { name: "General Knowledge", question: "What is the most useless thing in the world?", options: ["Script writer in a Salman film", "Heroine in a Salman film", "Audience in a Salman film", "CRED points"], answer: "CRED points", explanation: "CRED points have no real monetary value. The question also considered 'script writer in a Salman film' very seriously before landing here." },
      { name: "Mission Star", question: "Which of the following is NOT a real restaurant?", options: ["Mere Babu Ne Khana Khaya", "Tandoori", "Wah Mote Wah", "Maa Ke Pakode"], answer: "Maa Ke Pakode", explanation: "All others are real restaurants that exist in Delhi. 'Maa Ke Pakode' is the made-up one. Delhi restaurant naming is a contact sport." },
      { name: "Canada", question: "Complete the Babbu Maan lyric — 'Babbu Maan ne revolver chak kyun si?'", options: [], answer: "Kabza lena si", explanation: "He wanted to take possession. A classic Babbu Maan song about the Punjab way of life. The host fought with his Gujarati co-writer to include this." },
      { name: "Over Achievers", question: "Abhishek Bachchan, along with disappointing his father, holds a Guinness World Record. What for?", options: [], answer: "Most public appearances by a film star in 12 hours", explanation: "He visited 7 cities in 12 hours while promoting Delhi-6. Nobody guessed this. The host had to reveal it sadly." },
    ]
  },
  {
    id: 4, label: "Episode 4", panelists: "Azeem Banatwalla · Varun Thakur · Kautuk Srivastava",
    categories: [
      { name: "Plants", question: "What was the title of Smriti Irani's debut novel in 2022?", options: ["Kyunki Minister Bhi Kabhi Actor Thi", "Meri Aandhi Aur Rahul Gandhi", "Lal Salaam", "Main Tulsi Tere Aangan Ki"], answer: "Lal Salaam", explanation: "Smriti Irani's debut novel is Lal Salaam. The other options parody her famous TV show and character." },
      { name: "Struggling Actor", panelSpecific: true, question: "Which of the following roles has Varun Thakur NOT played?", options: ["Hero ka dost in Jab Tak Hai Jaan", "Casting assistant in Veer", "Only friend to Kautuk Srivastava", "A son his father can be proud of"], answer: "A son his father can be proud of", explanation: "Options A, B, C are real. D is the fictional one — a dig at his career. Varun famously got his own question wrong." },
      { name: "Papa the Great", question: "ICC Chairman Jay Shah is lovingly called what by cricket fans after an entertaining match?", options: ["Script Writer", "Chhota-Mota Bhai", "Greek God", "A meritorious candidate totally deserving of his position"], answer: "Script Writer", explanation: "Jay Shah is sarcastically called 'Script Writer' by fans who find India's match outcomes suspiciously convenient. Son of Home Minister Amit Shah." },
      { name: "National Monuments", question: "The land on which Antilla was built was originally allocated for what purpose?", options: ["Orphanage for underprivileged children", "Rehabilitation of abused trees", "Charity hospital for cancer patients", "Another blot on the city"], answer: "Orphanage for underprivileged children", explanation: "The land was allocated for an orphanage, sold far below market value in 2002, and became home to one of the world's most expensive private residences." },
      { name: "White People", question: "Directors Abbas-Mustan have a lesser-known third brother. What is his name?", options: ["Saifuddin Varmawala", "Mohammad Varmawala", "Hussain Varmawala", "Azeem Banatwalla"], answer: "Hussain Varmawala", explanation: "Abbas-Mustan (the Alibhai Burmawalla brothers) do have a real third brother named Hussain. Azeem was option D as a joke since he also wears white." },
      { name: "Chess Prodigy", question: "The chess influencer who beat Viswanathan Anand in a charity stream said only an idiot would do what?", options: ["Cheat in a charity chess stream", "Start a podcast", "Call corruption a good thing", "Do an MBA"], answer: "Do an MBA", explanation: "He stated doing an MBA is something only an idiot would do. 'Start a podcast' was a tempting wrong answer." },
      { name: "Roadies", question: "Who is the visionary behind the E20 ethanol fuel policy?", options: ["Vikram Sarabhai", "APJ Abdul Kalam", "Steve Jobs", "Shri Nitin Gadkari Ji"], answer: "Shri Nitin Gadkari Ji", explanation: "Road Transport Minister Nitin Gadkari championed the E20 policy. The original critical question was changed mid-recording because the host got nervous." },
      { name: "Popular Opinion", question: "What is the most irrelevant thing in the world right now?", options: ["Govinda", "Print Media", "Khamba's YouTube channel", "Congress Party"], answer: "Congress Party ad in Print Media", explanation: "The host accepted 'Congress Party ad in print media' — combining two options for maximum irrelevance." },
    ]
  },
  {
    id: 5, label: "Episode 5", panelists: "Rahul Subramanian · Gaurav Kapoor · Sumaira Sheikh",
    categories: [
      { name: "Make in India", question: "Which of the following is NOT the name of an actual Dongri don?", options: ["Karim Lala", "Mamu Langda", "Tariq Takla", "Moin Totla", "Yusuf Batla", "Shahrukh Khagla"], answer: "Shahrukh Khagla", explanation: "A–E are real Dongri gangster names. Shahrukh Khagla is fictional. Though honestly all of them sound like they could go either way." },
      { name: "Toxic Boss", question: "Which of the following is a real Narayana Murthy quote?", options: ["First get a life then worry about work-life balance", "How long can you stare at your wife on Sunday, get to office", "Tum saala gulam log hamesha jooti ke neeche rahega", "Paodex maliye kaam pe chaliye"], answer: "How long can you stare at your wife on Sunday, get to office", explanation: "This is a real Narayana Murthy quote advocating 70-hour work weeks. The others are fabricated. His wife probably has thoughts about this." },
      { name: "Large Language Model", question: "Shashi Tharoor wrote the following description about what? '__ is a cloud, a whisper, a perfect dream... a delicate, weightless martial equivalent of a Beethoven symphony'", options: ["Indian Democracy", "Sanju Samson batting", "Idli", "His deck"], answer: "Idli", explanation: "Shashi Tharoor used this elaborate paragraph to describe idli. He was not wrong but he could have just said 'soft rice cake'." },
      { name: "Real Jesus", question: "Which of the following Gautams is the best Gautam?", options: ["Gautam Singhania", "Gautam Adani", "Gautam Gambhir", "Yami Gautam"], answer: "Gautam Adani", explanation: "Confirmed by the host. Objectively the most Gautam of all Gautams. Built ports, airports, and a media empire from scratch." },
      { name: "Indian Farmer", question: "A viral reel showed a foreign woman mistaking Amitabh Bachchan's photo for someone who did what for a living?", options: ["Appeared in Panama Papers", "Cured Polio", "Manufactured Papad", "Recorded Annoying Caller Tunes"], answer: "Manufactured Papad", explanation: "A viral reel showed a foreign woman assuming the legendary actor made papad for a living. India's cinematic legacy: misidentified as a papad manufacturer." },
      { name: "Sell Out", question: "Which legendary lyricist wrote the Ching's noodles brand jingle for Ranveer Singh?", options: ["Prasoon Joshi", "Varun Grover", "Gulzar", "Javed Akhtar"], answer: "Gulzar", explanation: "Gulzar wrote 'Ping pong paade ka ching dada hoon, aawara khwabon ka shahzada hoon' for Ching's noodles. A man can eat." },
      { name: "Shooting Star", question: "What activity at Oxford brought back Malala Yousafzai's trauma of being shot by the Taliban?", options: ["Smoking a bong", "Eating Kabuli pulao", "Listening to Ankhiyon se goli maare", "Watching Four More Shots Please"], answer: "Smoking a bong", explanation: "She wrote in her memoir that smoking a bong at Oxford University brought back the trauma of being shot. The connection is left as an exercise for the reader." },
    ]
  },
  {
    id: 6, label: "Episode 6", panelists: "Kaustubh Agarwal · Ashish Solanki · Rajat Sood",
    categories: [
      { name: "Choos Mera", question: "Which of these technologies was NOT developed at Chalmers University in Sweden?", options: ["Ultrasound", "Tetra Pak", "Bluetooth", "Facial Recognition", "Asthma Inhaler", "Nicotine Gum", "Dialysis Machine", "Circumcision"], answer: "Circumcision", explanation: "All others (ultrasound, Tetra Pak, Bluetooth, facial recognition, asthma inhaler, nicotine gum, dialysis machine) were genuinely developed at Chalmers. Circumcision predates Swedish engineering." },
      { name: "Military Technology", question: "Sonar was inspired by dolphins. How many vaginas does a dolphin have?", options: [], answer: "1", explanation: "Dolphins have one. Aashish deduced 'ek toh rehti hogi' and was correct." },
      { name: "HR Activity", question: "Which of the following is NOT written behind a ricksha?", options: ["Nobody remains virgin, life f***s everyone", "Don't disturb, I am married, I am already very disturbed", "Jara kam pi meri rani, bahut mahanga hai Iraq ka paani", "Kripya horn na bajayein, sarkar ne pehle hi baja rakhi hai"], answer: "Jara kam pi meri rani, bahut mahanga hai Iraq ka paani", explanation: "Options A, B, D are real ricksha philosophies. Option C is written on TRUCKS, not rickshas — because trucks consume more oil, hence Iraq (oil). Ricksha drivers have boundaries." },
      { name: "90s Kids", question: "Looney Tunes' Tasmanian Devil was inspired by real creatures in Tasmania. How many vaginas does the Tasmanian Devil have?", options: [], answer: "2", explanation: "The Tasmanian Devil has two vaginas. Rajat deduced this correctly. This is what education should look like." },
      { name: "Shankar Mahadevan", question: "Hospitals reported a rise in respiratory infections in Delhi. What could possibly be the reason?", options: ["Nehru's chain smoking", "Tandoor making too many naans", "Rekha Gupta doing Anulom Vilom", "Stray dogs farting"], answer: "All of the above", explanation: "The host said 'all of the above' and gave everyone 10 points. Delhi's air is a collaborative effort." },
      { name: "Useless Brother", question: "Which of the following is something Abhinav Kashyap (Anurag's brother) has actually said?", options: ["Main raaste pe aa gaya toh Salman mujhpe gaadi charha dega", "Kuch bhi bolo Lawrence Bishnoi kaam toh acha hi kar raha hai", "Thappad se dar nahi lagta, podcast se lagta hai", "Woh dil mein bhi aata hai aur samajh mein bhi aata hai, bas jail mein nahi aata"], answer: "Main raaste pe aa gaya toh Salman mujhpe gaadi charha dega", explanation: "He genuinely said this about Salman Khan. The others are fabricated. Abhinav has lived a very specific life." },
      { name: "Demonetization", question: "What is the best app to sell your old phone with home pickup and instant payment?", options: ["Spotify", "Cashify", "Shopify", "Sanchar Saathi App"], answer: "Cashify", explanation: "The show's sponsor. A wildly convenient answer to a wildly leading question." },
      { name: "Beatles", question: "The Beatles' Blackbird was inspired by a bird in Rishikesh. How many vaginas does a blackbird have?", options: [], answer: "0", explanation: "Birds have a cloaca — a single rear opening that is not classified as a vagina. Zero vaginas. Aashish guessed 1 and was wrong. This whole category was about anatomy." },
    ]
  },
  {
    id: 7, label: "Episode 7", panelists: "Anubhav Singh Bassi · Aakash Gupta · Shreeja Chaturvedi",
    categories: [
      { name: "Below Poverty Line", question: "The Bangladesh Premier League (BPL) — which of these bizarre events did NOT happen in it?", options: ["Match fixing", "Players boycotted over bounced cheques", "Scarcity of cricket balls during practice", "Could not afford Hawk-Eye review", "Bus driver refused to return players' kit bags as he wasn't paid", "Being grateful to India for independence"], answer: "Being grateful to India for independence", explanation: "All of A–E actually happened in the BPL. Bangladesh being grateful to India is the fictional option." },
      { name: "Crazy Ex", question: "Pakistan's Defence Minister recently made a tall claim about the IMF. What did he say?", options: ["Friendship over with IMF. China is my new best friend.", "Pakistan may not need loans after six months.", "Bob's the king — mera ghante ka game.", "My pledge is that I will be a pilot and save Pakistan."], answer: "Pakistan may not need loans after six months.", explanation: "Pakistan's Defence Minister actually said this. Pakistan has since needed more IMF loans. The imagination required." },
      { name: "Delhi MMS", question: "Which of the following is a direct quote from Manmohan Singh?", options: ["Criticism is the soul of democracy.", "History will be kinder to me.", "Keh do na keh do na, you are my son.", "Tussi ja rahe ho? Tussi na jao."], answer: "History will be kinder to me.", explanation: "Manmohan Singh said this reflecting on his tenure. History is still deliberating. Options C and D are filmi references." },
      { name: "PDA (Prayagraj Dev. Authority)", question: "An anti-corruption bureau came to catch a bribe at PDA. What happened?", options: ["Offering ₹1650 per head for catching monkeys", "PDA officials beat up the anti-corruption officer", "Charging ₹500 fee for organising a protest", "Refusing application to rename Gandwa Gaon"], answer: "PDA officials beat up the anti-corruption officer", explanation: "The PDA officials beat up the officer who came to catch their bribe. A bold strategy. All other options also happened in India, just not at PDA." },
      { name: "Male Feminist", question: "What was the most unrealistic thing in the film Animal?", options: ["A pilot having sex while flying the plane", "A group of Sardars going to the UK and still coming back", "Everyone understanding whatever Rashmika was saying", "Ranbir sleeping with only two women"], answer: "Ranbir sleeping with only two women", explanation: "Given the film's hyper-masculine themes, two is an absurdly low number. Options A, B, C all track for that film's world." },
      { name: "Only Fans", question: "Which of the following has NOT happened in Udit Narayan's life?", options: ["Was compared to Asaram Bapu", "Lead actor in Nepal's highest-grossing film", "Sang in court to convince wife to drop a complaint", "Sang in a Hollywood film"], answer: "Sang in court to convince wife to drop a complaint", explanation: "This actually happened to a different person. Udit Narayan was Nepal's top film actor, has been compared to Asaram Bapu, and has sung in Hollywood." },
      { name: "Indian PM", question: "Which of these Veer Pahadiya jokes should Pranit More avoid making?", options: ["Knock knock. Veer who? Veer Pahadiya hoon.", "Difference between Veer Das and Veer Pahadiya: only one has a future in Bollywood.", "Why did Veer Pahadiya cross the road? To check if there were fans.", "All of them."], answer: "All of them.", explanation: "Pranit More was attacked by a mob for cracking Veer Pahadiya jokes. The answer is to avoid all of them. This is the only safe advice." },
    ]
  },
  {
    id: 8, label: "Episode 8", panelists: "Hoezaay · Urooj Ashfaq · Rahul Subramanian",
    categories: [
      { name: "Ancient Weapons", question: "Which punchline did comedy legend Sunil Pal bring to life, inspired by the film Raanjhanaa?", options: ["Ranjana mein hai Sonam, Kerala mein manate hain Onam.", "Mere pyare Ranjana, bartan saare maanjhna.", "Ranjhana hua hai tera, Salman ke saath hai Shera.", "Ranjana se door bhaago kyunki is picture ka naam hai Ranjana Ranjana Ranjana."], answer: "Mere pyare Ranjana, bartan saare maanjhna.", explanation: "Sunil Pal's actual punchline — a play on the film title as a domestic chore pun. Half the audience laughed when it was read out, confirming it." },
      { name: "Punchable Face", question: "Which of the following is NOT a real Shakib Al Hasan controversy?", options: ["Named in a murder case", "Quit his team over the phone", "Slapped a fan", "Obsessively spoke about laddoo with Suresh Raina"], answer: "Obsessively spoke about laddoo with Suresh Raina", explanation: "Named in a murder case, quitting over the phone, and slapping a fan are all real. The laddoo conversation with Raina was the fabricated option." },
      { name: "Dosti Bani Rahe", question: "Which of these is a tagline used by the Adani Group?", options: ["Modi hai toh mumkin hai.", "Money hai toh honey hai.", "Marunga sar pe, hagega ghar pe.", "Hum karke dikhate hain.", "Tedha hai par mera hai.", "Don ko pakadna mushkil hi nahi, namumkin hai."], answer: "Hum karke dikhate hain.", explanation: "Adani Group's official tagline is 'Hum karke dikhate hain' (We show by doing). The others are either government slogans or Bollywood dialogue." },
      { name: "Jurassic Park", question: "Which song was picturised on Dino Morea?", options: ["In Dino Dil Mera", "Char dinon ka pyaar o rabba, lambi judaai", "Morya re Morya re", "Ye sheher hai Aman ka, yahaan ki fizaaein nivaali"], answer: "Char dinon ka pyaar o rabba, lambi judaai", explanation: "This song was on Dino Morea. Rahul had no logical reason but guessed correctly based on pure instinct. Option D is an in-show joke about cameraman Aman." },
      { name: "Rebel Kid", question: "Umar Khalid has been in jail under NSA for nearly half a decade. Which college did he go to?", options: [], answer: "JNU (Jawaharlal Nehru University)", explanation: "Urooj answered immediately, which prompted the host to joke about 'anti-national activities by Urooj' for knowing this so quickly." },
      { name: "Aunty Number One", question: "What did Neeta Ambani dress up as at her Jamnagar Halloween party?", options: [], answer: "Audrey Hepburn", explanation: "Wrong guesses included Deadpool, Wonder Woman, Nicole Kidman, and Captain Planet before someone landed on Audrey Hepburn." },
      { name: "Veer Pahadiya", question: "A viral 2019 photo of Mount Everest showed which surprising problem faced by climbers?", options: ["Global vomit", "Open defecation", "Littered garbage", "Traffic jams", "Blind guy taking forever", "Delhi guys"], answer: "Traffic jams", explanation: "The viral 2019 Everest photo showed a massive queue of climbers near the summit — essentially a traffic jam at 8,000 metres." },
    ]
  },
  {
    id: 9, label: "Episode 9", panelists: "Anirban Dasgupta · Biswajit Sarkar · Prashasti Singh",
    categories: [
      { name: "Beef", question: "Which of the following is the biggest beef right now?", options: ["Arjun Kapoor and Instagram", "Kunal Kamra and startup founders", "Gautam Gambhir and winning home Test series", "Anil Dasgupta and Rohan Desai", "Modi and press conference"], answer: "Modi and press conference", explanation: "Modi has never held a formal press conference as Prime Minister of India. The longest-running beef in the country." },
      { name: "Nepotism", question: "Who is Ibrahim Ali Khan's real mother?", options: [], answer: "Gauri Khan", explanation: "Ibrahim Ali Khan is Shah Rukh Khan's son. His mother is Gauri Khan. Biswajit had near-zero Bollywood knowledge but figured it out." },
      { name: "Sonam Bewafa Hai", question: "Sonam Wangchuk was arrested under the National Security Act. What was the charge?", options: ["Claiming Linkin Park's 'So Long' is about him", "Criticising the film Dhurrandar", "Using a vacuum cleaner to deliver a baby on campus", "Plotting a violent revolt against the government"], answer: "Plotting a violent revolt against the government", explanation: "The NSA charge was 'plotting violent revolt' — widely seen as excessive for a peaceful environmental activist demanding Ladakh's statehood." },
      { name: "Call From Mother", question: null, options: [], answer: "Bonus category — no penalty, points for picking", explanation: "Whoever picked this got bonus points; whoever didn't was penalised -22. Anirban picked it wisely.", isTrap: true },
      { name: "Do Bhai Dono Tabahi", panelSpecific: true, question: "Between Khamba and Rohan Desai, which disease have they NOT collectively suffered from?", options: ["Kidney Stones", "Tuberculosis", "Pancreatitis", "Hepatitis A", "Cancer", "Testicular Torsion", "Piles"], answer: "Piles", explanation: "Between the two of them, they've had kidney stones, tuberculosis, pancreatitis, hepatitis A, cancer, and testicular torsion — but not piles. Yet." },
      { name: "Phir Se Ud Chala", question: "What did Vijay Mallya buy at a Harrods auction using money he saved by not paying Kingfisher employees?", options: ["A middle finger for RBI", "Gandhi's glasses", "Tipu Sultan's sword", "Modi's degrees", "Frequent flyer points"], answer: "Tipu Sultan's sword", explanation: "He bought it in 2016, it disappeared for 6 years, then he sold it at auction in 2023 for 10x the price and kept all the money." },
      { name: "Gayi Padosan", question: "Which item was NOT stolen from Sheikh Hasina's house when protesters stormed it in 2024?", options: ["Raw fish", "A blouse", "Her suitcase", "A rice cooker", "Chicken korma", "iPhone 16 128GB"], answer: "iPhone 16 128GB", explanation: "Protesters looted raw fish, clothing, and cookware. The iPhone 16 was the joke option. The host added a Cashify price plug." },
      { name: "Chaar Bottle Vard Ka", question: "Which Ravi Shastri quote went viral after India's Test win in Australia?", options: ["Ganpat, chal daaru la", "I only believe in Jassi bhai", "Thodi der ke liye gote munh mein the", "I got 99 problems and the pitch ain't one"], answer: "Thodi der ke liye gote munh mein the", explanation: "Ravi Shastri's remark on live TV — roughly 'for a while things were in the mouth' — went viral for its unintentional double entendre." },
    ]
  },
  {
    id: 10, label: "Episode 10", panelists: "Ashish Solanki · Shreya Priya Roy · Omkar Yadav",
    categories: [
      { name: "Garbage", question: null, options: [], answer: "+20 just for picking this category", explanation: "Very few people in India pick garbage, so Swachh Bharat Abhiyan rewards you with 20 bonus points. No question. Just vibes.", isTrap: true },
      { name: "Sleeping Beauty", question: "Which of the following is NOT on the ECI's free election symbol list?", options: ["Baby walker", "Road roller", "Lacy frock", "Noodle bowl", "Nail cutter", "Extension board"], answer: "Road roller", explanation: "Road roller was withdrawn from the list around 2015-16 as ECI deemed it 'too aggressive'. Baby walker, lacy frock, noodle bowl, nail cutter, and extension board remain valid election symbols." },
      { name: "Things Naazi Se (BYJU's)", question: "Which of the following is a real BYJU's sales tactic?", options: ["Pushing loans on low-income parents without consent", "Shaming parents into buying products", "Tracking free accounts to guilt-trip parents", "Refusing cancellation and refund requests", "Falsely claiming an 8-year-old earned millions", "All of the above"], answer: "All of the above", explanation: "BYJU's was documented using all five tactics. The company went bankrupt in 2024. The revolution in education looked different than advertised." },
      { name: "Learn University", question: "Which is an actual research patent by Galgotias University?", options: ["International Base at Break-Neck Speed: A Reality", "Strategic Appropriation of Foreign IP: A Robot Dog", "Satellite Image Reader to Track Minorities: A Necessity", "System and Method to Control Devices Through Mental Activities: A Thesis"], answer: "System and Method to Control Devices Through Mental Activities: A Thesis", explanation: "Galgotias University filed more patents than all IITs combined in 2022-23. This is one of them. The Coronavirus-Thali paper is another." },
      { name: "Feku (Neeraj Chopra)", question: "What did the MC at Neeraj Chopra's wedding actually ask the couple?", options: ["Aapke yahan bachpan mein nahi ho jata ye sab?", "Thoda aur north mein paida hote toh javelin ne hi kuch aur phenk rahe hote.", "Ladai ke time kya aap ek dusre pe cheezein fenkte ho?", "Waise aapka javelin kitna lamba hai?"], answer: "Ladai ke time kya aap ek dusre pe cheezein fenkte ho?", explanation: "The MC asked if they throw things at each other during fights — a javelin pun. It became a viral moment from the wedding." },
      { name: "Fat Boy Slim (Adnan Sami)", question: "What has Adnan Sami done to prove his loyalty to India after becoming a citizen in 2016?", options: ["Called for renaming Mysore Park to 'Mysore Shri'", "Killed a chicken because it was doing 'park park pak'", "Told AR Rahman to go back to Pakistan", "When asked why not celebrating 14th August, replied 'I will do it tomorrow'"], answer: "When asked why not celebrating 14th August, replied 'I will do it tomorrow'", explanation: "When asked why he wasn't celebrating Pakistan's Independence Day on 14th Aug, he said he'd celebrate it tomorrow — i.e., on India's Independence Day, 15th August. Commitment." },
      { name: "Naam Bade Darshan Chhote", question: "Rajpal Yadav said what should be added to Indian jails?", options: ["Welcome drink", "Live dosa counter", "Early check-in late check-out", "Height-wise line for lunch and dinner", "Waiting lounge for execution", "Special smoking zones"], answer: "Special smoking zones", explanation: "Post-arrest, Rajpal Yadav publicly demanded special smoking zones in jails. A celebrity's first prison reform thought." },
    ]
  },
  {
    id: 11, label: "Episode 11", panelists: "Gurleen Pannu · Rahul Dua · Gaurav Gupta",
    categories: [
      { name: "Bhabhi Ji Ghar Pe Hai", question: "What contribution are Punjabis making in Italy?", options: ["Providing arms to the Italian mafia", "Helping lose weight through bhangra classes", "Helping rear cows for cheese production", "Reviving the wine industry by drinking too much"], answer: "Helping rear cows for cheese production", explanation: "Punjabis in Italy are working as cattle herders for the dairy and cheese industry — a direct import of Punjab's agricultural DNA." },
      { name: "Thar Drivers", question: "What is the most popular cosmetic surgery among men according to the American Society of Plastic Surgeons?", options: [], answer: "Gynecomastia surgery (man boob removal)", explanation: "Male breast tissue reduction is the top cosmetic surgery for men globally. Nobody on the panel guessed this." },
      { name: "Drive to Survive", question: "Which hashtag did Rishabh Pant use in his viral response to Urvashi Rautela's hints about a relationship?", options: ["#TakeItEasyUrvashi", "#MeraPichchaChhodoBehen", "#AajaMeriGaariMeinBaithJa", "#ZindaHoonYaarKafiHai", "#OStreeKalAana"], answer: "#MeraPichchaChhodoBehen", explanation: "Rishabh's post ended with #MeraPichchaChhodoBehen after calling out people who lie in interviews for meager popularity." },
      { name: "Tumse Na Ho Payega", question: "Rahul Gandhi's YouTube channel comment section was flooded with congratulations. What achievement were they celebrating?", options: ["Completing 10,000 steps", "Meeting half the criteria of being Baaziger", "Crossing 10 million YouTube subscribers", "Getting through a speech without becoming a meme"], answer: "Crossing 10 million YouTube subscribers", explanation: "Rahul Gandhi's channel hit 10 million subscribers. His supporters celebrated. The channel quality remains a topic of debate." },
      { name: "Indian Army (Shark Tank)", question: "Who was the best host of Shark Tank India?", options: ["Ranvijay Singh", "Aashish Solanki", "Sahiba Bali", "Kullu"], answer: "All of the above", explanation: "The host accepted 'all of the above'. Rahul Dua had previously hosted Shark Tank India, making this a particularly diplomatic answer." },
      { name: "Sell Out", panelSpecific: true, question: "Since Khamba's viral clip saying he hates comics selling their soul for brands, which of the following has HE done?", options: ["Instagram reel for Mogu Mogu", "Read WOW Skincare features on stage", "Used his podcast to promote Pond's", "Bought a smartwatch to promote Boat on Valentine's", "Put a minute-long ad in Episode 8 to promote Khakee"], answer: "All of the above", explanation: "He did all five. The flag-bearer of artistic integrity has planted the flag in every brand deal available." },
      { name: "Sardar Patel", question: "According to new US State Department guidelines, what is now valid grounds for rejecting a US visa?", options: ["Pronouncing Trump's name as 'Donald'", "Asking a female visa officer to show Bob and Vagene", "Being too fat", "Calling Kamala's campaign 'Kamala Ka Hamla'"], answer: "Being too fat", explanation: "The US has introduced obesity as valid grounds for visa rejection — arguing obese immigrants may burden the healthcare system." },
      { name: "Silence of the Lamps (China Boycott)", question: "Which of the following did NOT happen during the China boycott after Galwan?", options: ["Man threw Chinese TV out of window", "Protesters burned Kim Jong-un effigy thinking he was Chinese", "Delhi's Defence Colony declared war on China", "Taking away Mieyang Cheng's film roles"], answer: "Taking away Mieyang Cheng's film roles", explanation: "The TV toss, Kim Jong-un effigy mistake, and Defence Colony LOC all actually happened. Mieyang Cheng's film roles were not affected. Yet." },
    ]
  },
  {
    id: 12, label: "Episode 12", panelists: "Shamik Chakrabarti · Chirag Panjwani · Shreeja Chaturvedi",
    categories: [
      { name: "Tukde Tukde Gang", question: "Before splitting India into India and Pakistan, what was Mountbatten's original plan?", options: ["Nehru ke bakkad bakkad Bombay bo bo", "Divide into 10 Premier League teams", "Divide into 500+ provinces", "Divide into SRK, Salman, Aamir fans"], answer: "Divide into 500+ provinces", explanation: "Mountbatten's original plan was over 500 princely states. He settled on two. We got the condensed chaos package." },
      { name: "That 70s Show", question: "Which of the following did NOT happen during Indira Gandhi's Emergency?", options: ["Using government machinery to intimidate opposition", "Censoring media from criticising government", "Jailing students and protesters", "Tightening censorship laws over artists", "Forcing actors to lip sync 'Indira hai toh India hai'"], answer: "Forcing actors to lip sync 'Indira hai toh India hai'", explanation: "A, B, C, D all happened during the 1975–77 Emergency. The lip-sync mandate was the fake option. Everything else is in the history books." },
      { name: "True Caller", question: "What unlikely business model have gangsters like Lawrence Bishnoi adopted?", options: ["Shooting outside cafes", "Forcing musicians to upload on gangsters' YouTube channels", "Starting OnlyFans accounts", "Human trafficking as bhangra bookings", "IAS coaching centres"], answer: "Forcing musicians to upload on gangsters' YouTube channels", explanation: "Gangsters have been directing musicians to upload their music on the gangsters' own YouTube channels for ad revenue. A surprisingly modern diversification." },
      { name: "No Country for Old Men", question: "What was LK Advani's profession in the 1960s before politics?", options: ["Professional rath driver", "Professional film critic", "Professional PM wannabe", "Professional building demolition expert", "Amateur hair model"], answer: "Professional film critic", explanation: "LK Advani was a film enthusiast who wrote movie reviews in magazines in the 1960s. A man of hidden depths." },
      { name: "Star of David", question: "Which of the following has NOT happened in Govinda's life?", options: ["Paid ₹5 lakh for slapping a fan", "Charged a dozen bananas and a coconut for a film", "Shot himself in the foot", "Rejected a role in Avatar saying not his vibe", "His duplicate performed to 15,000 when he didn't show", "Threatened Karan Johar in Rajinikanth style"], answer: "His duplicate performed to 15,000 when he didn't show up", explanation: "All other incidents are on record. The duplicate story was fabricated. Govinda's real life requires no embellishment." },
      { name: "Tiger Shroff", question: "The astrologer who predicted Nepal's Gen-Z protests also predicted which of the following?", options: ["Kejriwal will be released from prison", "India's Got Latent will return for Season 2", "Prithviraj will never make a comeback", "Nobody will understand what 'six-seven' means", "Aman will get a laptop"], answer: "Prithviraj will never make a comeback", explanation: "The same astrologer who called Nepal's protests and India's energy crisis also predicted Prithviraj Sukumaran's permanent exit from relevance." },
      { name: "White Woman", question: "In which of the following films did Rakhi Gulzar NOT play a widow?", options: ["Karan Arjun", "Ram Lakhan", "Border", "Baaziger", "Rudaali", "Tapasya", "Anaari"], answer: "Tapasya", explanation: "Tapasya (1976) is the only film listed where her character never gets married — so no widowhood possible. She won Filmfare Best Actress for it." },
    ]
  },
  {
    id: 13, label: "Season Finale", panelists: "Abish Mathew · Kaneez Surka · Rohan Joshi",
    categories: [
      { name: "Mother", question: null, options: [], answer: "Minus 20 for picking this", explanation: "Rohan picked it. -20 points. No question. Some categories are traps.", isTrap: true },
      { name: "Home Alone", question: "When Omar Abdullah was released from house arrest (post-Article 370) and COVID lockdown was announced the same day, which meme did he share?", options: [], answer: "A meme about being locked down all over again immediately after getting out", explanation: "Omar went from political house arrest directly into national COVID lockdown. He shared a meme capturing the irony. Perfect comedic timing by the universe." },
      { name: "Mia Khalifa", question: "When the Burj Khalifa opened in 2010, trucks were queued every night to take something away. What?", options: ["Poop", "Escorts", "Pet camels", "Empty champagne bottles", "Influencers shouting Habibi come to Dubai"], answer: "Poop", explanation: "The Burj Khalifa was not connected to the city sewage system when it opened. Poop trucks came every night. This is also the origin of the 'Dubai chocolate' meme." },
      { name: "AIB", question: "What is the AIB (Aeronautical Institute of Bangladesh)'s crowning achievement?", options: ["Got Sheikh Hasina business class tickets while escaping", "Airdropped fake Aadhaar cards through paper planes", "Attacked Mannat after Mustafizur was kicked out", "Only private aviation institute approved by Civil Aviation Authority of Bangladesh"], answer: "Only private aviation institute approved by Civil Aviation Authority of Bangladesh", explanation: "AIB's actual achievement is being the only approved private aviation training institute in Bangladesh. The other options are more entertaining but fictional." },
      { name: "Mera Number One", question: "Morarji Desai accidentally revealed something crucial to Pakistani General Zia-ul-Haq. What did he spill?", options: ["Batting order of Indian cricket team", "That Dharam 1 was better than Dharam 2", "Listens to Pakistani Coke Studio on incognito", "That India knew about Pakistan's nuclear site at Kahuta", "That Rekha and Amitabh were together"], answer: "That India knew about Pakistan's nuclear site at Kahuta", explanation: "In a phone call, Morarji Desai told Zia-ul-Haq that Indian intelligence knew about Pakistan's secret nuclear facility at Kahuta. A significant intelligence blunder." },
      { name: "Yeh Toh Tatti Hai", question: "Companies have been hiring improv comedy actors. For what purpose?", options: [], answer: "To train AI on human emotion", explanation: "Tech companies are using improv actors' natural emotional range to create training data for AI emotion models. Comedy is now infrastructure." },
      { name: "Barbecue Nation", question: "During the 2026 Iran-Israel conflict, which of the following did NOT happen?", options: ["Tourists left 1-star reviews after a Dubai hotel was attacked", "Pakistan PM tweeted 'I condom' instead of 'I condemn'", "Qatar evacuated 147 show horses", "US aircraft carrier overflowed with poop"], answer: "Pakistan PM tweeted 'I condom'", explanation: "Dubai hotel 1-star reviews, 147 Qatar show horses, and the poop aircraft carrier all actually happened. The PM tweet was fabricated." },
      { name: "Choti Bachi Ho Kya", question: "When Jeffrey Epstein texted Anil Ambani in 2017 offering a 'tall Swedish blonde', how long did Anil take to reply 'Arrange that'?", options: [], answer: "20 seconds", explanation: "Reportedly 20 seconds — an almost immediate response. No deliberation. Full commitment." },
    ]
  }
]
